author:
  name: Egotistical Giraffe
baseURL: 'https://egotisticalgiraffe.com'
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Providing Security, Privacy  and Anonymity tools to the modern citizen
title: Egotistical Giraffe
theme: Blogpaper
