version: '3.7'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt
      - ./public:/var/www/egotisticalgiraffe.com
