version: '3.7'

services:
  hugo:
    image: klakegg/hugo
    command: server
    volumes:
      - './:/src'
    networks:
      - reverse_proxy_net
    environment:
      HUGO_ENV_ARG: 'production'
  nginx:
    image: nginx
    depends_on:
      - hugo
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt
      - ./public:/var/www/egotisticalgiraffe.com
    networks:
      - reverse_proxy_net
networks:
  reverse_proxy_net:
